name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  tests:
    name: tests
    runs-on: macos-14
    timeout-minutes: 20
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Run Example
      run: | 
        clang -framework CoreGraphics -framework Foundation -framework Metal newbufnocopy.m -o newbufnocopy && ./newbufnocopy